In [156]:
import numpy as np
import pandas as pd

In [157]:
df=pd.read_csv("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\Feature_engineering\\Random_forest\\dog_health\\dog_health_dataset_10000.csv.xls")

In [158]:
df.head()

,Dog Breed,Dog Age,Dog Weight,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,Disease,Precautions,Treatment,Emergency
0,Labrador Retriever,9,44.2,Hair loss,Diarrhea,Coughing,Skin rash,Sneezing,Fungal Infection,Keep skin dry,Antifungal cream,No
1,German Shepherd,7,20.6,Skin rash,Hair loss,Diarrhea,Limping,Sneezing,Allergy,Avoid allergens,Antihistamines,No
2,Poodle,15,5.4,Loss of appetite,Vomiting,Diarrhea,Limping,Lethargy,Digestive Disorder,Balanced diet,Diet change,No
3,Labrador Retriever,12,44.3,Skin rash,Sneezing,Limping,Hair loss,Lethargy,Allergy,Avoid allergens,Antihistamines,No
4,Rottweiler,2,21.2,Skin rash,Hair loss,Sneezing,Vomiting,Fever,Allergy,Avoid allergens,Antihistamines,No

In [159]:
col = list(df.columns)
for i in col:
    
    print(f"{df[i].value_counts()}",end="")

Dog Breed
Dachshund             1046
Boxer                 1014
Labrador Retriever    1013
Rottweiler            1009
Golden Retriever       998
Poodle                 992
Beagle                 989
Bulldog                983
Pug                    983
German Shepherd        973
Name: count, dtype: int64Dog Age
9     704
14    691
2     688
1     687
5     686
10    679
12    678
13    669
3     668
4     663
6     655
11    648
7     647
8     633
15    604
Name: count, dtype: int64Dog Weight
33.5    40
35.5    39
10.0    38
14.0    36
16.3    36
        ..
14.1    13
36.0    12
43.7    11
12.4    11
3.0     11
Name: count, Length: 421, dtype: int64Symptom 1
Vomiting            1052
Loss of appetite    1035
Sneezing            1023
Fever               1008
Lethargy             998
Coughing             987
Diarrhea             983
Hair loss            980
Limping              975
Skin rash            959
Name: count, dtype: int64Symptom 2
Hair loss           1047
Limping             1033
Diarrhea            1011
Lethargy            1008
Sneezing             997
Skin rash            997
Fever                987
Coughing             981
Vomiting             980
Loss of appetite     959
Name: count, dtype: int64Symptom 3
Lethargy            1032
Hair loss           1017
Fever               1012
Sneezing            1011
Skin rash           1004
Vomiting             999
Loss of appetite     995
Limping              992
Diarrhea             987
Coughing             951
Name: count, dtype: int64Symptom 4
Loss of appetite    1030
Diarrhea            1024
Coughing            1012
Skin rash           1009
Hair loss           1001
Vomiting             998
Sneezing             997
Limping              986
Lethargy             981
Fever                962
Name: count, dtype: int64Symptom 5
Limping             1053
Hair loss           1033
Lethargy            1026
Loss of appetite    1014
Fever               1011
Diarrhea            1006
Sneezing            1005
Skin rash            962
Vomiting             955
Coughing             935
Name: count, dtype: int64Disease
Gastroenteritis       1052
Digestive Disorder    1035
Cold                  1023
Viral Infection       1008
Tick Fever             998
Kennel Cough           987
Parvovirus             983
Fungal Infection       980
Joint Pain             975
Allergy                959
Name: count, dtype: int64Precautions
Avoid outside food, give clean water    1052
Balanced diet                           1035
Keep dog warm                           1023
Isolate dog, maintain hygiene           1008
Regular tick control                     998
Avoid contact with infected dogs         987
Vaccination, avoid infected areas        983
Keep skin dry                            980
Avoid heavy exercise                     975
Avoid allergens                          959
Name: count, dtype: int64Treatment
Antibiotics              1985
IV fluids, medication    1052
Diet change              1035
Supportive care          1023
Antiviral medication     1008
Hospitalization           983
Antifungal cream          980
Pain relievers            975
Antihistamines            959
Name: count, dtype: int64Emergency
No     8009
Yes    1991
Name: count, dtype: int64

In [160]:
#df["symptoms"]=[df["Symptom 1"]+df["Symptom 2"]+df["Symptom 3"]+df["Symptom 4"]+df["Symptom 5"]]

In [161]:
df.columns

Index(['Dog Breed', 'Dog Age', 'Dog Weight', 'Symptom 1', 'Symptom 2',
       'Symptom 3', 'Symptom 4', 'Symptom 5', 'Disease', 'Precautions',
       'Treatment', 'Emergency'],
      dtype='object')

In [162]:
df.head()

,Dog Breed,Dog Age,Dog Weight,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,Disease,Precautions,Treatment,Emergency
0,Labrador Retriever,9,44.2,Hair loss,Diarrhea,Coughing,Skin rash,Sneezing,Fungal Infection,Keep skin dry,Antifungal cream,No
1,German Shepherd,7,20.6,Skin rash,Hair loss,Diarrhea,Limping,Sneezing,Allergy,Avoid allergens,Antihistamines,No
2,Poodle,15,5.4,Loss of appetite,Vomiting,Diarrhea,Limping,Lethargy,Digestive Disorder,Balanced diet,Diet change,No
3,Labrador Retriever,12,44.3,Skin rash,Sneezing,Limping,Hair loss,Lethargy,Allergy,Avoid allergens,Antihistamines,No
4,Rottweiler,2,21.2,Skin rash,Hair loss,Sneezing,Vomiting,Fever,Allergy,Avoid allergens,Antihistamines,No

In [163]:
#df.drop(columns=['Symptom 1','Symptom 2','Symptom 3','Symptom 4', 'Symptom 5','Precautions','Treatment', 'Emergency'],inplace=True)

In [164]:
df.head()

,Dog Breed,Dog Age,Dog Weight,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,Disease,Precautions,Treatment,Emergency
0,Labrador Retriever,9,44.2,Hair loss,Diarrhea,Coughing,Skin rash,Sneezing,Fungal Infection,Keep skin dry,Antifungal cream,No
1,German Shepherd,7,20.6,Skin rash,Hair loss,Diarrhea,Limping,Sneezing,Allergy,Avoid allergens,Antihistamines,No
2,Poodle,15,5.4,Loss of appetite,Vomiting,Diarrhea,Limping,Lethargy,Digestive Disorder,Balanced diet,Diet change,No
3,Labrador Retriever,12,44.3,Skin rash,Sneezing,Limping,Hair loss,Lethargy,Allergy,Avoid allergens,Antihistamines,No
4,Rottweiler,2,21.2,Skin rash,Hair loss,Sneezing,Vomiting,Fever,Allergy,Avoid allergens,Antihistamines,No

In [165]:
#df["symptoms"].value_counts()

In [166]:
df["Dog Breed"].value_counts()

Dog Breed
Dachshund             1046
Boxer                 1014
Labrador Retriever    1013
Rottweiler            1009
Golden Retriever       998
Poodle                 992
Beagle                 989
Bulldog                983
Pug                    983
German Shepherd        973
Name: count, dtype: int64

In [167]:
df["Disease"].value_counts()

Disease
Gastroenteritis       1052
Digestive Disorder    1035
Cold                  1023
Viral Infection       1008
Tick Fever             998
Kennel Cough           987
Parvovirus             983
Fungal Infection       980
Joint Pain             975
Allergy                959
Name: count, dtype: int64

In [168]:
#combile symptoms
symptoms_columns = ["Symptom 1","Symptom 2","Symptom 3","Symptom 4","Symptom 5"]
df["All_symptoms"]= df[symptoms_columns].values.tolist()
df.drop(columns=symptoms_columns,inplace=True)

# multilabelbinarizer

In [169]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb= MultiLabelBinarizer()
symptom_encoded = mlb.fit_transform(df["All_symptoms"])
df.drop(columns="All_symptoms",inplace=True)

In [170]:
symptom_encoded.dtype

dtype('int64')

In [171]:
#convert symptom_encode into data frame
symptom_encoded_df = pd.DataFrame(symptom_encoded,columns=mlb.classes_,index=df.index)

In [172]:
df= pd.concat([df,symptom_encoded_df],axis=1)

In [173]:
df.head()

,Dog Breed,Dog Age,Dog Weight,Disease,Precautions,Treatment,Emergency,Coughing,Diarrhea,Fever,Hair loss,Lethargy,Limping,Loss of appetite,Skin rash,Sneezing,Vomiting
0,Labrador Retriever,9,44.2,Fungal Infection,Keep skin dry,Antifungal cream,No,1,1,0,1,0,0,0,1,1,0
1,German Shepherd,7,20.6,Allergy,Avoid allergens,Antihistamines,No,0,1,0,1,0,1,0,1,1,0
2,Poodle,15,5.4,Digestive Disorder,Balanced diet,Diet change,No,0,1,0,0,1,1,1,0,0,1
3,Labrador Retriever,12,44.3,Allergy,Avoid allergens,Antihistamines,No,0,0,0,1,1,1,0,1,1,0
4,Rottweiler,2,21.2,Allergy,Avoid allergens,Antihistamines,No,0,0,1,1,0,0,0,1,1,1

In [174]:
df.drop(columns=["Precautions","Treatment","Emergency"],inplace=True)

In [175]:
df["final_Disease"]=df["Disease"]
df.drop(columns="Disease",inplace=True)
df.head()

,Dog Breed,Dog Age,Dog Weight,Coughing,Diarrhea,Fever,Hair loss,Lethargy,Limping,Loss of appetite,Skin rash,Sneezing,Vomiting,final_Disease
0,Labrador Retriever,9,44.2,1,1,0,1,0,0,0,1,1,0,Fungal Infection
1,German Shepherd,7,20.6,0,1,0,1,0,1,0,1,1,0,Allergy
2,Poodle,15,5.4,0,1,0,0,1,1,1,0,0,1,Digestive Disorder
3,Labrador Retriever,12,44.3,0,0,0,1,1,1,0,1,1,0,Allergy
4,Rottweiler,2,21.2,0,0,1,1,0,0,0,1,1,1,Allergy

In [176]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [177]:
x.head()

,Dog Breed,Dog Age,Dog Weight,Coughing,Diarrhea,Fever,Hair loss,Lethargy,Limping,Loss of appetite,Skin rash,Sneezing,Vomiting
0,Labrador Retriever,9,44.2,1,1,0,1,0,0,0,1,1,0
1,German Shepherd,7,20.6,0,1,0,1,0,1,0,1,1,0
2,Poodle,15,5.4,0,1,0,0,1,1,1,0,0,1
3,Labrador Retriever,12,44.3,0,0,0,1,1,1,0,1,1,0
4,Rottweiler,2,21.2,0,0,1,1,0,0,0,1,1,1

In [178]:
y.head()

0      Fungal Infection
1               Allergy
2    Digestive Disorder
3               Allergy
4               Allergy
Name: final_Disease, dtype: object

In [179]:
x["Dog Breed"].value_counts()

Dog Breed
Dachshund             1046
Boxer                 1014
Labrador Retriever    1013
Rottweiler            1009
Golden Retriever       998
Poodle                 992
Beagle                 989
Bulldog                983
Pug                    983
German Shepherd        973
Name: count, dtype: int64

In [180]:
#one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("encoder",OneHotEncoder(),["Dog Breed"])],remainder="passthrough")
x=pd.DataFrame(ct.fit_transform(x))

In [181]:
x.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0

In [182]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)

In [183]:
y

array([3, 0, 2, ..., 2, 6, 5], shape=(10000,))

In [184]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [185]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test =scaler.transform(x_test)

In [186]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
x_train_smote,y_train_smote = sm.fit_resample(x_train,y_train)

In [187]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=4)
rf.fit(x_train_smote,y_train_smote)

RandomForestClassifier(random_state=4)

In [188]:
y_pred = rf.predict(x_test)

In [189]:
from     sklearn.metrics import accuracy_score
print(f"accuracy_score ={accuracy_score(y_test,y_pred)*100}")

accuracy_score =19.15

In [191]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
ada= AdaBoostClassifier()
gra = GradientBoostingClassifier()
ada.fit(x_train_smote,y_train_smote)
y_pred_ada= ada.predict(x_test)
print(f"accuracy_score ={accuracy_score(y_test,y_pred_ada)*100}")

accuracy_score =20.4

In [192]:
gra.fit(x_train_smote,y_train_smote)
y_pred_gra= gra.predict(x_test)
print(f"accuracy_score ={accuracy_score(y_test,y_pred_ada)*100}")

accuracy_score =20.4