In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Telegram Desktop\\Development-jourey\\machinelearningworks\\Feature_engineering\\decision_tree\\stroke_data\\stroke.csv.xls")

In [19]:
df["stroke"].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [20]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
df["bmi"]=imputer.fit_transform(df[["bmi"]])

In [22]:
x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [23]:
x

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked
...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.893237,never smoked
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked
5109,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer([("encoder",OneHotEncoder(),['gender','ever_married','work_type', 'Residence_type','smoking_status'])],remainder="passthrough")
x=pd.DataFrame(ct.fit_transform(x))

In [25]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [26]:
x.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,67.0,0.0,1.0,228.69,36.600000
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,61.0,0.0,0.0,202.21,28.893237
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,80.0,0.0,1.0,105.92,32.500000
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,49.0,0.0,0.0,171.23,34.400000
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,79.0,1.0,0.0,174.12,24.000000

In [27]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# smote

In [30]:
! pip install imblearn

Requirement already satisfied: imblearn in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imblearn) (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (2.3.2)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.17.0)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from imblearn.over_sampling import SMOTE

sm= SMOTE(random_state=42)
x_train_smote,y_train_smote = sm.fit_resample(x_train,y_train)