In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\seaborn_works\\plyastore\\plystore.csv")

In [3]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [6]:
df["Reviews"].value_counts()

Reviews
0         596
1         272
2         214
3         175
4         137
         ...
885         1
88486       1
603         1
1195        1
398307      1
Name: count, Length: 6002, dtype: int64

In [7]:
df_copy =df.copy()

In [21]:
df_copy["Reviews"]=df_copy["Reviews"].astype("int")

In [13]:
df_copy["Reviews"]=df_copy["Reviews"].replace({"M":000000})

In [ ]:
df_copy[~df_copy["Reviews"].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [20]:
df_copy.drop(df_copy.index[10472],inplace=True)

In [22]:
df_copy[df_copy["Size"].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [36]:
#replay m iwth 000
#replace k with empty
df_copy["Size"]=df_copy["Size"].str.replace("M","000")
df_copy["Size"]=df_copy["Size"].str.replace("m","000")
df_copy["Size"]=df_copy["Size"].str.replace("k","")
df_copy["Size"]=df_copy["Size"].str.replace("K","")

In [34]:
df_copy.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [30]:
df_copy["Size"]=df_copy["Size"].replace("Varies with device",np.nan)

In [39]:
df_copy["Size"]=df_copy["Size"].astype("float")

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [40]:
df_copy["Price"]=df_copy["Price"].str.replace("$","")

In [41]:
df_copy["Price"].unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [42]:
df_copy["Price"]=df_copy["Price"].astype("float")

In [ ]:
df_copy["Installs"]=df_copy["Installs"].str.replace("+","")
df_copy["Installs"]=df_copy["Installs"].str.replace(",","")

AttributeError: Can only use .str accessor with string values!

In [47]:
df_copy["Installs"].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0])

In [58]:
df_copy["Installs"]=df_copy["Installs"].astype("int")
df_copy["Size"]=df_copy["Size"].astype("str")

In [ ]:
df_copy["Size"]=np.where(df_copy["Size"].str.contains(r"\."),df_copy["Size"].str.replace(".","",regex=False).str[:-1],df_copy["Size"])\

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14624\1285262178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy["Size"]=np.where(df_copy["Size"].str.contains(r"\."),df_copy["Size"].str.replace(".","",regex=False).str[:-1],df_copy["Size"])

In [50]:
df_copy["Last Updated"].unique()

<DatetimeArray>
['2018-01-07 00:00:00', '2018-01-15 00:00:00', '2018-08-01 00:00:00',
 '2018-06-08 00:00:00', '2018-06-20 00:00:00', '2017-03-26 00:00:00',
 '2018-04-26 00:00:00', '2018-06-14 00:00:00', '2017-09-20 00:00:00',
 '2018-07-03 00:00:00',
 ...
 '2015-11-23 00:00:00', '2012-06-17 00:00:00', '2015-02-27 00:00:00',
 '2013-12-18 00:00:00', '2012-02-06 00:00:00', '2014-11-25 00:00:00',
 '2016-05-19 00:00:00', '2014-01-20 00:00:00', '2014-02-16 00:00:00',
 '2014-03-23 00:00:00']
Length: 1377, dtype: datetime64[ns]

In [49]:
df_copy["Last Updated"]=pd.to_datetime(df_copy["Last Updated"])

In [52]:
df_copy["year"]=df_copy["Last Updated"].dt.year

In [53]:
df_copy["month"]=df_copy["Last Updated"].dt.month
df_copy["day"]=df_copy["Last Updated"].dt.day

In [54]:
df_copy.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,year,month,day
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,2018,1,7
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,2018,1,15
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,2018,8,1
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,2018,6,8
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,2018,6,20

In [56]:
df_copy[df_copy["App"].duplicated()].shape

(1181, 16)

In [60]:
df_copy=df_copy.drop_duplicates(subset=["App"],keep="first")

In [61]:
df_copy[df_copy["App"].duplicated()].shape

(0, 16)

In [65]:
df_copy["Size"].unique()

array(['19000', '14000', '8', '25000', '2', '5', '29000', '33000', '3',
       '28000', '12000', '20000', '21000', '37000', '17000', '39000',
       '31000', '4', '7', '23000', '6', '9', '11000', '24000', 'nan',
       '15000', '10000', '1', '26000', '56000', '57000', '35000', '54000',
       '201', '27000', '16000', '38000', '32000', '18000', '52000',
       '30000', '22000', '13000', '73000', '42000', '55000', '23',
       '51000', '41000', '48000', '46000', '40000', '61000', '66000',
       '79', '118', '44000', '695', '18', '53000', '45000', '63000',
       '49000', '77000', '70000', '10', '36000', '84000', '97000',
       '47000', '556', '526', '76000', '59000', '78000', '72000', '43000',
       '334', '34000', '93000', '65000', '79000', '100000', '58000',
       '50000', '68000', '64000', '67000', '60000', '94000', '232',
       '99000', '624', '95000', '41', '292', '11', '80000', '74000',
       '62000', '69000', '75000', '98000', '85000', '82000', '96000',
       '87000', '71000', '86000', '91000', '81000', '92000', '83000',
       '88000', '704', '862', '899', '378', '266', '375', '975', '980',
       '89000', '696', '544', '525', '920', '779', '853', '720', '713',
       '772', '318', '58', '241', '196', '857', '51', '953', '865', '251',
       '930', '540', '313', '746', '203', '26', '314', '239', '371',
       '220', '730', '756', '91', '293', '17', '74', '14', '317', '78',
       '924', '902', '818', '81', '939', '169', '45', '475', '965',
       '90000', '545', '61', '283', '655', '714', '93', '872', '121',
       '322', '976', '172', '238', '549', '206', '954', '444', '717',
       '210', '609', '308', '705', '306', '904', '473', '175', '350',
       '383', '454', '421', '70', '812', '442', '842', '417', '412',
       '459', '478', '335', '782', '721', '430', '429', '192', '200',
       '460', '728', '496', '816', '414', '506', '887', '613', '243',
       '569', '778', '683', '592', '319', '186', '840', '647', '191',
       '373', '437', '598', '716', '585', '982', '222', '219', '55',
       '948', '323', '691', '511', '951', '963', '25', '554', '351', '27',
       '82', '208', '913', '514', '551', '29', '103', '898', '743', '116',
       '153', '209', '353', '499', '173', '597', '809', '122', '411',
       '400', '801', '787', '237', '50', '643', '986', '97', '516', '837',
       '780', '961', '269', '20', '498', '600', '749', '642', '881', '72',
       '656', '601', '221', '228', '108', '940', '176', '33', '663', '34',
       '942', '259', '164', '458', '245', '629', '28', '288', '775',
       '785', '636', '916', '994', '309', '485', '914', '903', '608',
       '500', '54', '562', '847', '957', '688', '811', '270', '48', '329',
       '523', '921', '874', '981', '784', '280', '24', '518', '754',
       '892', '154', '860', '364', '387', '626', '161', '879', '39',
       '970', '170', '141', '160', '144', '143', '190', '376', '193',
       '246', '73', '658', '992', '253', '420', '404', '470', '226',
       '240', '89', '234', '257', '861', '467', '157', '44', '676', '67',
       '552', '885', '1020', '582', '619'], dtype=object)

In [66]:
df_copy.to_csv("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\seaborn_works\\plyastore\\cleated_data_set.csv")