In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\Feature_engineering\\Random_forest\\cancerdata\\breast-cancer.csv.xls")

In [19]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [20]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [21]:
x=df.iloc[:,2:]
y=df.iloc[:,1]

In [22]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, concave points_mean, symmetry_mean, fractal_dimension_mean, radius_se, texture_se, perimeter_se, area_se, smoothness_se, compactness_se, concavity_se, concave points_se, symmetry_se, fractal_dimension_se, radius_worst, texture_worst, perimeter_worst, area_worst, smoothness_worst, compactness_worst, concavity_worst, concave points_worst, symmetry_worst, fractal_dimension_worst]
Index: []

[0 rows x 32 columns]

In [23]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [24]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y =le.fit_transform(y)

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
x_train_smote,y_train_smote = sm.fit_resample(x_train,y_train)

In [15]:
from   sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=3)
rf.fit(x_train_smote,y_train_smote)
y_pred = rf.predict(x_test)
from sklearn.metrics import accuracy_score,f1_score
print(f"accuracy_score ={accuracy_score(y_pred,y_test)*100}")
print(f"f1_score ={f1_score(y_pred,y_test)*100}")

accuracy_score =96.49122807017544
f1_score =95.34883720930233

In [16]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,f1_score
models=[KNeighborsClassifier,GaussianNB,DecisionTreeClassifier,RandomForestClassifier]
for model in models:
    md=model()
    md.fit(x_train_smote,y_train_smote)
    ypred=md.predict(x_test)
    print("======",model,"=======")
    print("accuracy",accuracy_score(y_test,ypred)*100)
    print("f1 score",f1_score(y_test,ypred)*100)

====== <class 'sklearn.neighbors._classification.KNeighborsClassifier'> =======
accuracy 95.6140350877193
f1 score 94.25287356321839
====== <class 'sklearn.naive_bayes.GaussianNB'> =======
accuracy 96.49122807017544
f1 score 95.23809523809523
====== <class 'sklearn.tree._classes.DecisionTreeClassifier'> =======
accuracy 96.49122807017544
f1 score 95.55555555555556
====== <class 'sklearn.ensemble._forest.RandomForestClassifier'> =======
accuracy 96.49122807017544
f1 score 95.34883720930233

In [25]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
ada= AdaBoostClassifier()
gra = GradientBoostingClassifier()
ada.fit(x_train_smote,y_train_smote)
y_pred_ada= ada.predict(x_test)
print(f"accuracy_score ={accuracy_score(y_test,y_pred_ada)*100}")

accuracy_score =97.36842105263158

In [26]:
! pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (2.3.2)
Requirement already satisfied: scipy in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (1.17.0)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 1.8/101.7 MB 15.2 MB/s eta 0:00:07
   --- ------------------------------------ 7.9/101.7 MB 22.7 MB/s eta 0:00:05
   ----- ---------------------------------- 13.1/101.7 MB 23.0 MB/s eta 0:00:04
   ------ --------------------------------- 16.8/101.7 MB 21.5 MB/s eta 0:00:04
   ------- -------------------------------- 20.2/101.7 MB 20.3 MB/s eta 0:00:05
   --------- ------------------------------ 24.1/101.7 MB 20.0 MB/s eta 0:00:04
   ----------- ---------------------------- 28.6/101.7 MB 20.2 MB/s eta 0:00:04
   ------------ --------------------------- 32.8/101.7 MB 20.1 MB/s eta 0:00:04
   -------------- ------------------------- 36.7/101.7 MB 19.9 MB/s eta 0:00:04
   --------------- ------------------------ 39.8/101.7 MB 19.4 MB/s eta 0:00:04
   ---------------- ----------------------- 42.2/101.7 MB 18.7 MB/s eta 0:00:04
   ----------------- ---------------------- 44.0/101.7 MB 18.0 MB/s eta 0:00:04
   ------------------ --------------------- 46.7/101.7 MB 17.4 MB/s eta 0:00:04
   ------------------- -------------------- 48.8/101.7 MB 17.1 MB/s eta 0:00:04
   -------------------- ------------------- 50.9/101.7 MB 16.5 MB/s eta 0:00:04
   -------------------- ------------------- 53.0/101.7 MB 16.1 MB/s eta 0:00:04
   --------------------- ------------------ 54.8/101.7 MB 15.6 MB/s eta 0:00:04
   ---------------------- ----------------- 57.1/101.7 MB 15.3 MB/s eta 0:00:03
   ----------------------- ---------------- 59.5/101.7 MB 15.1 MB/s eta 0:00:03
   ------------------------ --------------- 61.3/101.7 MB 14.8 MB/s eta 0:00:03
   ------------------------- -------------- 63.7/101.7 MB 14.5 MB/s eta 0:00:03
   ------------------------- -------------- 65.3/101.7 MB 14.2 MB/s eta 0:00:03
   -------------------------- ------------- 66.6/101.7 MB 13.9 MB/s eta 0:00:03
   -------------------------- ------------- 67.9/101.7 MB 13.6 MB/s eta 0:00:03
   --------------------------- ------------ 69.2/101.7 MB 13.3 MB/s eta 0:00:03
   --------------------------- ------------ 70.3/101.7 MB 12.9 MB/s eta 0:00:03
   ---------------------------- ----------- 71.3/101.7 MB 12.6 MB/s eta 0:00:03
   ---------------------------- ----------- 72.6/101.7 MB 12.4 MB/s eta 0:00:03
   ---------------------------- ----------- 73.7/101.7 MB 12.2 MB/s eta 0:00:03
   ----------------------------- ---------- 75.0/101.7 MB 11.9 MB/s eta 0:00:03
   ------------------------------ --------- 76.3/101.7 MB 11.8 MB/s eta 0:00:03
   ------------------------------ --------- 77.6/101.7 MB 11.6 MB/s eta 0:00:03
   ------------------------------- -------- 78.9/101.7 MB 11.4 MB/s eta 0:00:02
   ------------------------------- -------- 80.5/101.7 MB 11.3 MB/s eta 0:00:02
   -------------------------------- ------- 82.1/101.7 MB 11.2 MB/s eta 0:00:02
   -------------------------------- ------- 83.6/101.7 MB 11.1 MB/s eta 0:00:02
   --------------------------------- ------ 84.9/101.7 MB 11.0 MB/s eta 0:00:02
   --------------------------------- ------ 86.2/101.7 MB 10.9 MB/s eta 0:00:02
   ---------------------------------- ----- 87.8/101.7 MB 10.8 MB/s eta 0:00:02
   ----------------------------------- ---- 89.1/101.7 MB 10.7 MB/s eta 0:00:02
   ----------------------------------- ---- 90.7/101.7 MB 10.6 MB/s eta 0:00:02
   ------------------------------------ --- 92.0/101.7 MB 10.5 MB/s eta 0:00:01
   ------------------------------------ --- 92.8/101.7 MB 10.4 MB/s eta 0:00:01
   ------------------------------------ --- 93.8/101.7 MB 10.2 MB/s eta 0:00:01
   ------------------------------------- -- 94.6/101.7 MB 10.1 MB/s eta 0:00:01
   ------------------------------------- -- 95.7/101.7 MB 9.9 MB/s eta 0:00:01
   ------------------------------------- -- 96.5/101.7 MB 9.8 MB/s eta 0:00:01
   -------------------------------------- - 97.3/101.7 MB 9.7 MB/s eta 0:00:01
   -------------------------------------- - 98.3/101.7 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 9.3 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
from xgboost import XGBClassifier
xg=XGBClassifier()
xg.fit(x_train_smote,y_train_smote)
y_pred_xg= xg.predict(x_test)
print(f"accuracy_score ={accuracy_score(y_test,y_pred_xg)*100}")

accuracy_score =96.49122807017544

In [28]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,f1_score
models=[KNeighborsClassifier,GaussianNB,DecisionTreeClassifier,RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier,XGBClassifier]
for model in models:
    md=model()
    md.fit(x_train_smote,y_train_smote)
    ypred=md.predict(x_test)
    print("======",model,"=======")
    print("accuracy",accuracy_score(y_test,ypred)*100)
    print("f1 score",f1_score(y_test,ypred)*100)

====== <class 'sklearn.neighbors._classification.KNeighborsClassifier'> =======
accuracy 95.6140350877193
f1 score 94.25287356321839
====== <class 'sklearn.naive_bayes.GaussianNB'> =======
accuracy 96.49122807017544
f1 score 95.23809523809523
====== <class 'sklearn.tree._classes.DecisionTreeClassifier'> =======
accuracy 95.6140350877193
f1 score 94.3820224719101
====== <class 'sklearn.ensemble._forest.RandomForestClassifier'> =======
accuracy 98.24561403508771
f1 score 97.67441860465115
====== <class 'sklearn.ensemble._weight_boosting.AdaBoostClassifier'> =======
accuracy 97.36842105263158
f1 score 96.47058823529412
====== <class 'sklearn.ensemble._gb.GradientBoostingClassifier'> =======
accuracy 96.49122807017544
f1 score 95.34883720930233
====== <class 'xgboost.sklearn.XGBClassifier'> =======
accuracy 96.49122807017544
f1 score 95.34883720930233