In [91]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\LENOVO\\OneDrive\\Documents\\housing_price_dataset.csv")

In [92]:
df.head()

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [93]:
df.isnull().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [94]:
x= df.iloc[:,:-1]
y= df.iloc[:,1]

In [95]:
#encoding

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([("encoder",OneHotEncoder(),["Neighborhood"])],remainder="passthrough",)
x= pd.DataFrame(ct.fit_transform(x))

In [97]:
x

         0    1    2       3    4    5       6
0      1.0  0.0  0.0  2126.0  4.0  1.0  1969.0
1      1.0  0.0  0.0  2459.0  3.0  2.0  1980.0
2      0.0  1.0  0.0  1860.0  2.0  1.0  1970.0
3      0.0  0.0  1.0  2294.0  2.0  1.0  1996.0
4      0.0  1.0  0.0  2130.0  5.0  2.0  2001.0
...    ...  ...  ...     ...  ...  ...     ...
49995  1.0  0.0  0.0  1282.0  5.0  3.0  1975.0
49996  0.0  1.0  0.0  2854.0  2.0  2.0  1988.0
49997  0.0  1.0  0.0  2979.0  5.0  3.0  1962.0
49998  1.0  0.0  0.0  2596.0  5.0  2.0  1984.0
49999  1.0  0.0  0.0  1572.0  5.0  3.0  2011.0

[50000 rows x 7 columns]

In [98]:
#xtest split

In [99]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [100]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test- scaler.transform(x_test)
x_train

array([[ 1.41416053, -0.70832689, -0.70586087, ..., -1.3480363 ,
         1.22893434,  1.72130583],
       [-0.7071333 , -0.70832689,  1.41670978, ...,  1.34247591,
         1.22893434, -0.40556085],
       [-0.7071333 , -0.70832689,  1.41670978, ...,  1.34247591,
         0.00343141, -1.37231842],
       ...,
       [-0.7071333 , -0.70832689,  1.41670978, ...,  0.4456385 ,
         0.00343141,  1.18958916],
       [-0.7071333 , -0.70832689,  1.41670978, ..., -0.4511989 ,
        -1.22207152, -0.30888509],
       [ 1.41416053, -0.70832689, -0.70586087, ...,  1.34247591,
         1.22893434, -1.56566994]], shape=(40000, 7))

In [101]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

In [102]:
from sklearn.metrics import r2_score,accuracy_score

print(f"r2_score = {r2_score(y_test,y_pred)}")
print(f"accuracy_score = {accuracy_score(y_test,y_pred)*100}")

r2_score = -1.0341337570923748
accuracy_score = 28.050000000000004